# Generated by Django 5.1.5 on 2025-01-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='inner_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='main_head',
            field=models.TextField(blank=True, null=True),
        ),
    ]
