# Generated by Django 5.1.5 on 2025-01-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_service_inner_title_alter_service_main_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceheader',
            name='picture',
            field=models.ImageField(upload_to='serviceHeader'),
        ),
    ]
