# Generated by Django 5.1.5 on 2025-01-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
